version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5433:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=scaner
      - POSTGRES_USER=scaner
      - POSTGRES_DB=scaner_db
